#!/bin/bash
# Context Tree - Simple Installation Script
# Downloads the AI Documentation Field Guide (quick start for incremental approach)

set -e

REPO_BASE="https://raw.githubusercontent.com/RossH3/context-tree/main"

echo "📦 Installing AI Documentation Field Guide..."
echo ""

# Download the field guide (the distilled lessons)
echo "  Downloading AI_DOCUMENTATION_FIELD_GUIDE.md..."
curl -sSL "$REPO_BASE/AI_DOCUMENTATION_FIELD_GUIDE.md" -o "AI_DOCUMENTATION_FIELD_GUIDE.md"

echo ""
echo "✅ Installation complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 What You Got"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "AI_DOCUMENTATION_FIELD_GUIDE.md"
echo "  - Practical lessons from 6 months of real-world usage"
echo "  - Lightweight navigation hub pattern (CLAUDE.md)"
echo "  - Incremental capture approach (Rule of Two)"
echo "  - Real examples from production codebase"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Two Approaches Available"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. SIMPLE (Incremental Approach):"
echo "   - Start with minimal CLAUDE.md (~200 lines)"
echo "   - Add insights when friction repeats (Rule of Two)"
echo "   - No upfront structure needed"
echo "   - Best for: Most projects, ongoing work"
echo ""
echo "   Read: AI_DOCUMENTATION_FIELD_GUIDE.md (Part 6)"
echo ""
echo "2. STRUCTURED (Brownfield Onboarding):"
echo "   - 3-phase orchestrated workflow"
echo "   - Domain expert interview (captures institutional knowledge)"
echo "   - Quality-gated documentation generation"
echo "   - Best for: Legacy codebases, team onboarding"
echo ""
echo "   Install: curl -sSL https://raw.githubusercontent.com/RossH3/context-tree/main/install-advanced.sh | bash"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Read the Field Guide:"
echo "   open AI_DOCUMENTATION_FIELD_GUIDE.md"
echo ""
echo "2. For incremental approach:"
echo "   - Create minimal CLAUDE.md (see Field Guide Part 1)"
echo "   - Start working and add insights when needed"
echo ""
echo "3. For structured approach:"
echo "   - Run the advanced installer (command above)"
echo "   - Follow the 3-phase orchestrated workflow"
echo ""
echo "4. After building initial docs:"
echo "   - You can delete AI_DOCUMENTATION_FIELD_GUIDE.md"
echo "   - Or keep it for reference on documentation quality"
echo ""
